DATA:
  DATASET: imagenet
  IMG_SIZE: 448
  BATCH_SIZE: 16
  DATA_PATH: '/home/apulis-test/teamdata/yz_dataset/fuqi/'
  NAME_CLASSES: ["fuqi","ok"]

MODEL:
  TYPE: swin
  NAME: yz_fuqi_1108
  DROP_PATH_RATE: 0.2
  NUM_CLASSES: 2
  RESUME: ''
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7

TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.1
  BASE_LR: 1.25e-4
  WARMUP_LR: 1.25e-7
  MIN_LR: 1.25e-6
